# Generated by Django 4.0.3 on 2022-03-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='D:\\Josh\\Documents\\year3\\CISC 325\\quampus\\backend\\static/images\\default-user.png', upload_to='D:\\Josh\\Documents\\year3\\CISC 325\\quampus\\backend\\static/images'),
        ),
    ]
