# Generated by Django 3.2.12 on 2022-03-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_residence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residence',
            old_name='alt',
            new_name='alt_name',
        ),
    ]
