# Generated by Django 4.0.3 on 2022-03-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='default-user.png', upload_to=''),
        ),
    ]
