# Generated by Django 4.0.3 on 2022-03-20 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_forumreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumreply',
            name='original_poster',
        ),
        migrations.AddField(
            model_name='forumreply',
            name='original_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_replies', to='api.forumpost'),
        ),
    ]
