# Generated by Django 4.0.3 on 2022-03-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_forumpost_created_forumreply_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
